### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by ShaohangXu** [yxyang/locomotion_simulation#3]
I am using pip install but I have a problem :

![2021-01-04 21-58-30屏幕截图](https://user-images.githubusercontent.com/24794138/103542612-26747180-4ed8-11eb-92b8-b61bed9beef8.png)

In setup.py,  module "extensions" has not been defined. 

This problem may be related to the PythonWrapAPI but I don't know how to fix it.

Another problem I have is, after I delete the above-mentioned line, pip install passed, but locomotion:A1GymEnv-v1 is still not registered with Gym.

Thank you for your help.

**Comment by yxyang** [comment]
Thanks for catching! The extensions were used when I had a different MPC module implemented in C++. For the current version it's not required. I simply forgot to delete it.

[This PR](https://github.com/yxyang/locomotion_simulation/pull/4) should fix it.
